"""extend_visitor

Revision ID: cddbf7aa0a2f
Revises: e500c4de0d62
Create Date: 2020-12-27 21:27:16.637838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddbf7aa0a2f'
down_revision = 'e500c4de0d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unique_visitor', sa.Column('ask_for_demo', sa.Boolean(), nullable=True))
    op.add_column('unique_visitor', sa.Column('finish_scheduling', sa.Boolean(), nullable=True))
    op.add_column('unique_visitor', sa.Column('start_scheduling', sa.Boolean(), nullable=True))
    op.add_column('unique_visitor', sa.Column('yes_for_demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unique_visitor', 'yes_for_demo')
    op.drop_column('unique_visitor', 'start_scheduling')
    op.drop_column('unique_visitor', 'finish_scheduling')
    op.drop_column('unique_visitor', 'ask_for_demo')
    # ### end Alembic commands ###
